# Generated by Django 5.1.6 on 2025-02-09 21:03

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="заголовок")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="описание"
                    ),
                ),
                ("content", models.TextField(verbose_name="содержимое")),
                ("slug", models.SlugField(max_length=255, verbose_name="URI")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        upload_to="uploads/%Y/%m/%d",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="опубликовано?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["created_at", "updated_at", "title"],
            },
        ),
    ]
