# Generated by Django 5.1.6 on 2025-03-02 08:35

import articles.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="содержимое"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                upload_to=articles.models.article_directory_path,
                verbose_name="изображение",
            ),
        ),
    ]
