# Generated by Django 5.2 on 2025-04-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_content_alter_article_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at", "-updated_at", "title"],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
