# Generated by Django 5.2 on 2025-04-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="published",
            new_name="is_published",
        ),
    ]
