# Generated by Django 5.2.1 on 2025-06-04 15:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DomainLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now=True)),
                (
                    'domain',
                    models.CharField(max_length=255, verbose_name='домен'),
                ),
            ],
            options={
                'verbose_name': 'Журнал доменов',
                'ordering': ('-timestamp',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now=True)),
                (
                    'address',
                    models.GenericIPAddressField(
                        unpack_ipv4=True, verbose_name='IP адрес'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Журнал IP',
                'ordering': ('-timestamp',),
                'abstract': False,
            },
        ),
    ]
