# Generated by Django 5.2.1 on 2025-05-31 07:34

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address",
                    models.GenericIPAddressField(
                        unpack_ipv4=True, verbose_name="IP адрес"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Журнал IP",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
