# Generated by Django 5.2.1 on 2025-06-04 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainlog',
            old_name='domain',
            new_name='name',
        ),
    ]
