# Generated by Django 5.2.1 on 2025-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tools', '0002_rename_domain_domainlog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlog',
            name='view_type',
            field=models.CharField(
                choices=[('whois', 'Whois'), ('nslookup', 'ns lookup')],
                max_length=16,
                null=True,
                verbose_name='тип представления',
            ),
        ),
    ]
